# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-22 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0002_auto_20180422_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='adresse',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='editeur',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='maison_edition',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='pages',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='series',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='url',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='volume',
            field=models.CharField(max_length=300),
        ),
    ]
