# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-22 19:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0003_auto_20180422_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteurs', models.CharField(help_text='Suivre le format suivant: Prenom1 Nom1 and Prénom2 Nom2 and ...', max_length=300)),
                ('titre', models.CharField(help_text="Le titre de l'article", max_length=300)),
                ('journal', models.CharField(help_text="Le nom du journal dans lequel l'article a été publié", max_length=300)),
                ('moi', models.PositiveIntegerField(help_text='De Janvier(1) à Décembre(12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('annee', models.PositiveIntegerField(help_text='Utilisez le format suivant: YYYY', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)])),
                ('pages', models.CharField(blank=True, help_text='Suire le format suivant: debut--fin,                     par exemple pour la page 9 à 16: 9--16', max_length=300)),
                ('volume', models.CharField(blank=True, max_length=300)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('issn', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteurs', models.CharField(help_text='Suivre le format suivant: Prenom1 Nom1 and Prénom2 Nom2 and ...', max_length=300)),
                ('titre', models.CharField(help_text="Le titre du livre dans lequel l'article est publié", max_length=300)),
                ('maison_edition', models.CharField(max_length=300)),
                ('annee', models.PositiveIntegerField(help_text='Utilisez le format suivant: YYYY', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)])),
                ('chapitre', models.CharField(blank=True, max_length=300)),
                ('pages', models.CharField(blank=True, help_text='Suire le format suivant: debut--fin,                     par exemple pour la page 9 à 16: 9--16', max_length=300)),
                ('volume', models.CharField(blank=True, max_length=300)),
                ('adresse', models.CharField(blank=True, help_text='Suivre le format suivant: Ville, Pays', max_length=300)),
                ('edition', models.IntegerField(blank=True, help_text='Mettre 1 pour première édition, 2 pour deuxième, etc.')),
                ('url', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='conference',
            name='isbn',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='adresse',
            field=models.CharField(blank=True, help_text='Suivre le format suivant: Ville, Pays', max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='editeur',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='maison_edition',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='pages',
            field=models.CharField(blank=True, help_text='Suire le format suivant: debut--fin,                     par exemple pour la page 9 à 16: 9--16', max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='series',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='conference',
            name='volume',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
