# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-22 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0004_auto_20180422_1906'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Livre',
        ),
    ]
