# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-22 20:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_app', '0006_rapporttechnique'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutrePublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(help_text='Suivre le format suivant: Prenom1 Nom1 and Prénom2 Nom2 and ...', max_length=300)),
                ('titre', models.CharField(help_text="Le titre du livre dans lequel l'article est publié", max_length=300)),
                ('annee', models.PositiveIntegerField(help_text='Utilisez le format suivant: YYYY', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)])),
                ('url', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TheseDoctorale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(help_text='Suivre le format suivant: Prenom1 Nom1 and Prénom2 Nom2 and ...', max_length=300)),
                ('titre', models.CharField(help_text="Le titre du livre dans lequel l'article est publié", max_length=300)),
                ('ecole', models.CharField(max_length=300)),
                ('departement', models.CharField(max_length=300)),
                ('annee', models.PositiveIntegerField(help_text='Utilisez le format suivant: YYYY', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)])),
                ('url', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='TheseMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(help_text='Suivre le format suivant: Prenom1 Nom1 and Prénom2 Nom2 and ...', max_length=300)),
                ('titre', models.CharField(help_text="Le titre du livre dans lequel l'article est publié", max_length=300)),
                ('ecole', models.CharField(max_length=300)),
                ('departement', models.CharField(max_length=300)),
                ('annee', models.PositiveIntegerField(help_text='Utilisez le format suivant: YYYY', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)])),
                ('url', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
